platform :ios, "7.0"

# ignore all warnings from all pods
inhibit_all_warnings!

pod 'Parse'
pod 'AFNetworking', '2.3.0'
pod 'Mantle'
pod 'BDBOAuth1Manager'
pod 'XLForm', '~> 2.0'
pod 'HMSegmentedControl', '~> 1.3.0'
pod 'AMRatingControl', '~> 1.3.0'
